osx_image: xcode10
language: swift

before_install: 
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet 
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet 
  - pod install --project-directory=Example 

script:
- pod lib lint --allow-warnings
