# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'


target 'U17Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for U17Demo
  pod 'SnapKit'
  pod 'Then'
  pod 'Moya'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'Reusable'
  pod 'LLCycleScrollView'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'HMSegmentedControl'
  pod 'IQKeyboardManagerSwift'
  pod 'EmptyDataSet-Swift'
  pod 'UINavigation-SXFixSpace'


  target 'U17DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'U17DemoUITests' do
    # Pods for testing
  end

end
